language: python
python:
        - "3.6"
sudo: required
install:
        - sudo pip install --upgrade pip
        - sudo pip install django==2.0.3
script:
        - cd web_server
        - python manage.py test

